---

- name: Include vars for cloud provider
  include_vars:
    file: "{{ cloud_provider }}.yml"
    name: "{{ cloud_provider }}"

- name: Dump gcp vars
  debug:
    var: gcp

- pause:

- name: Create a disk
  gcp_compute_disk:
    name: "{{ gcp['playground'] }}-disk"
    size_gb: 50
    source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
    zone: "{{ gcp['zone'] }}"
    project: "{{ gcp['project'] }}"
    auth_kind: "{{ gcp['cred_kind'] }}"
    service_account_file: "{{ gcp['cred_file'] }}"
    scopes: "{{ gcp['scopes'] }}"
    state: "{{ state | default('present') }}"
  register: disk

# - name: Create a network
#   gcp_compute_network:
#     name: "{{ gcp['playground'] }}-network"
#     project: "{{ gcp_project }}"
#     auth_kind: "{{ gcp_cred_kind }}"
#     service_account_file: "{{ gcp_cred_file }}"
#     scopes: "{{ gcp_scopes }}"
#     state: "{{ state | default('present') }}"
#   register: network

- name: Create an address
  gcp_compute_address:
    name: "{{ gcp['playground'] }}-address"
    region: "{{ gcp['region'] }}"
    project: "{{ gcp['project'] }}"
    auth_kind: "{{ gcp['cred_kind'] }}"
    service_account_file: "{{ gcp['cred_file'] }}"
    scopes: "{{ gcp['scopes'] }}"
    state: "{{ address_state | default('present') }}"
  register: address

- name: Create an instance
  gcp_compute_instance:
    name: "{{ gcp['playground'] }}-vm"
    machine_type: n1-standard-1
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    network_interfaces:
     # - network: "{{ network }}"
     - access_configs:
        - name: 'External NAT'
          nat_ip: "{{ address }}"
          type: 'ONE_TO_ONE_NAT'
    metadata:
      ssh-keys: "{{ gcp['ssh_user'] }}:{{ lookup('file', gcp['ssh_pubkey']) }}"
    zone: "{{ gcp['zone'] }}"
    project: "{{ gcp['project'] }}"
    auth_kind: "{{ gcp['cred_kind'] }}"
    service_account_file: "{{ gcp['cred_file'] }}"
    scopes: "{{ gcp['scopes'] }}"
    state: "{{ state | default('present') }}"
  register: instance

- name: Debug instance
  debug:
    msg:
      - "{{ instance }}"
      - "{{ address }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ address['address'] }}"
    port: 22
    delay: 10
    timeout: 60

- name: Add host to groupname
  add_host:
    hostname: "{{ address['address'] }}"
    groupname: gitlab

