---

external_roles:
  - name: ansible-role-gitlab
    # TODO: Revert once issue closed (https://github.com/geerlingguy/ansible-role-gitlab/issues/199)
    # source: https://github.com/geerlingguy/ansible-role-gitlab.git
    # version: 3.2.0
    source: https://github.com/AdamGoldsmith/ansible-role-gitlab.git
    version: fix/timeout
gitlab_external_url: "https://gitlab-01:4483/"
gitlab_git_data_dir: "/git-data"
